server:
  port: 8082

clickhouse:
  host: ${CH_HOST}
  port: ${CH_PORT}
  database: ${CH_DATABASE}
  username: ${CH_USERNAME}
  password: ${CH_PASSWORD}

spring:
  datasource:
    url: ${PSQL_URL}
    password: ${PSQL_PASSWORD}
    username: ${PSQL_USERNAME}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl:
          auto: validate


