server:
  port: 8082

clickhouse:
  host: localhost
  port: 8123
  database: metrics
  username: test
  password: test

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/monitoring
    password: test
    username: test

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl:
          auto: validate


  liquibase:
    enabled: false


  level:
    org:
      springframework:
        security: DEBUG

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855



springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    use-root-path: true